spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://i9b208.p.ssafy.io:8432/Square?useUniCode=yes&characterEncoding=UTF-8&serverTimezone=Asia/Seoul
    username: hihi
    password: 8811
  jpa:
    show-sql: true
    database: mysql
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.MySQL8Dialect
        discriminator:
          ignore_explicit_for_joined: true
    .open-in-view: false
  security:
    user:
      name: admin
      password: admin
  servlet:
    multipart:
      enabled: true
      max-file-size: 50MB
      max-request-size: 50MB

# JPA log
logging:
  level:
    org:
      hibernate:
        SQL: DEBUG
        type:
          descriptor:
            sql:
              BasicBinder: TRACE

# jwt
jwt:
  secret: d39gssddf6SsdahASDFFaesdGHJFDGjsdfsddfsdhSDS2HSZDasEsd48Os923459780012I4E3IdjSLOFJaseyH
  access:
    expiration: 1209600000 #  (1000L(ms -> s) * 60L(s -> m) * 60L(m -> h) * 24L(h -> 하루) * 14(2주))
    header: Authorization
    # expiration: 3600000 # 1시간(60분) (1000L(ms -> s) * 60L(s -> m) * 60L(m -> h))

  refresh:
    expiration: 1209600000 #  (1000L(ms -> s) * 60L(s -> m) * 60L(m -> h) * 24L(h -> 하루) * 14(2주))
    header: Authorization-refresh

server:
  port: 8811

# AWS
cloud:
  aws:
    s3:
      bucket: ssafy-square-bucket # .bucket
    region:
      static: ap-northeast-2
      auto: false
    stack:
      auto: false
    credentials:
      access-key: AKIAXFHB46BC5APX3VNV
      secret-key: 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


social:
  kakao:
    rest-api: 409915cf48a47370a92cea926084d5a1
    redirect-uri: http://localhost:3000/login/KakaoRedirect
  naver:
    client-id: C4jdFBfefASIcQgC9GDg
    client-secret: 8xQtnJy7L1
    redirect-uri: http://localhost:3000/login/NaverRedirect
    state: test


